### ISSUE TITLE
README.md記載項目を完成させてください

### ISSUE THREAD

**Issue by LeonTeraoka** [bananatips/Flask_app#1]
何を記載するべきでしょうか？

**Comment by rutko** [comment]
環境とツールは合わせた方が良いと思います。

環境とツールのセットアップ方法、Flaskの起動方法などを書いてあげると良さそうですが、一旦かけそうな部分だけ追加しました👍

開発するにあたってコミットメッセージはある程度揃えた方がいいのと一眼見て分かりやすくするべきかと思ったので、
Emoji prefixを設定してみました。
詳しくは[こちら](https://goodpatch.com/blog/beautiful-commits-with-emojis)を見てください🙏

**Comment by LeonTeraoka** [comment]
ご対応ご苦労様です。
Python は3.8.5にて統一を予定しておりますのでご承知おきください。
まあ、都度、更新していきましょう。
