### ISSUE TITLE
チャプター6のテンプレ作成前にちょっと待った！

### ISSUE THREAD

**Issue by LeonTeraoka** [bananatips/Flask_app#10]
足並みを揃えるために一度通話で相談させてください

**Comment by rutko** [comment]
今日は21時以降であれば空いています👍

**Comment by LeonTeraoka** [comment]
嘘乙です。
今日の21時以降はちょっと微妙ですが、調整の努力はしたいと思います。
1からこの間買ったsurfaceproでやろうと思ってますので、まずはlocalで立ち上がって、各urlがちゃんと開けるかを試そうと思ってますのでよろしくお願いいたします。

**Comment by rutko** [comment]
19時から1時間ほど外出しているので、終わり次第一応連絡します🙏

**Comment by LeonTeraoka** [comment]
とりあえず、先進んでください。
時間空き次第、内容確認いたしますので、よろしくお願いいたします。
