### ISSUE TITLE
ブランチの運用ルールについて、READMEに記載願います。

### ISSUE THREAD

**Issue by LeonTeraoka** [bananatips/Flask_app#5]
表題の件、認識を合わせたいので記載願います。

**Comment by rutko** [comment]
GitFlowに乗っ取ってブランチルールを作りました
詳しくは[こちら](https://dev.classmethod.jp/articles/introduce-git-flow/)を確認ください

**Comment by LeonTeraoka** [comment]
例えば feature/*****←この部分は何を基準に付けていますか？

**Comment by rutko** [comment]
ここはケースバイケースなので厳密には決めていませんが、
例えば
- 機能追加の場合　feature/add_XXXX
- アップデートなど feature/update_
- 文言修正などのバグではない修正 feature/fix_
- 削除など feature/remove_
とかのようにブランチ作っています👍

**Comment by LeonTeraoka** [comment]
回答どうも、ありがとうございます。
上記内容も備忘録のために、お手数ですがREADMEに記載願います。
